import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import PlainLayout from "@/components/master/Plain-Layout";
import { cookies } from "next/headers";
import SideNavbar from "@/components/master/SideNavbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Shohid Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const cookieStore = cookies();
    const token = cookieStore.get("token");
    let isLogin = false;
    isLogin = typeof token !== "undefined";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PlainLayout>
          {isLogin ? (
            <div className="flex ">
              <div>
                <SideNavbar />
              </div>
              {children}
            </div>
          ) : (
            <> {children}</>
          )}
        </PlainLayout>
      </body>
    </html>
  );
}
